@echo off
echo Starting setup...
cmd /c npx --yes create-vite@latest . --template react
echo Install standard...
cmd /c npm install
echo Install dependencies...
cmd /c npm install tailwindcss postcss autoprefixer framer-motion lucide-react recharts clsx tailwind-merge
echo Setup tailwind...
cmd /c npx tailwindcss init -p
echo Done.
